---
-
    CLASS: GND
    uri: http://bartoc.org/en/node/430
    url: http://www.dnb.de/DE/Standardisierung/GND/gnd_node.html
    prefLabel:
        en: Gemeinsame Normdatei    
    EXAMPLES:
      - uri: http://d-nb.info/gnd/4189143-0
      - notation: 118509624
-
    CLASS: OpenSKOS
    prefLabel:
        en: Europeana OpenSKOS API
    url: http://skos.europeana.eu/api
    EXAMPLES:
      - uri: http://data.europeana.eu/concept/loc
      - uri: http://id.loc.gov/authorities/subjects/sh2007003224
      - notation: 1500
-
    CLASS: Wikidata
    uri: http://bartoc.org/en/node/1940
    prefLabel:
        en: Wikidata
    url: https://www.wikidata.org/
    EXAMPLES:
      - notation: q42
      - uri: http://www.wikidata.org/entity/Q36578
-
    CLASS: Geonames
    uri: http://bartoc.org/en/node/1674
    prefLabel:
        en: Geonames
    url: http://geonames.org/
    EXAMPLES:
      - notation: 614540 
      - uri: http://sws.geonames.org/2918632/
-
    CLASS: ORCID
    uri: http://bartoc.org/en/node/2021
    prefLabel:
        en: ORCID
    url: http://orcid.org/
    SECRET:
      - ORCID_CLIENT_ID
      - ORCID_CLIENT_SECRET
    EXAMPLES:
      - notation: 0000-0002-7613-4123
      - uri: http://orcid.org/0000-0002-1825-0097
      - search: Carberry
-
    CLASS: BARTOC
    prefLabel:
        en: BARTOC
    url: http://bartoc.org/
    EXAMPLES:
      - uri: http://bartoc.org/en/node/430
      - uri: http://bartoc.org/en/node/109
      - search: Library
      - notation: 1715 # registry
-
    CLASS: VIAF
    prefLabel:
        en: VIAF
    altLabel:
        en:
            - Virtual International Authority File
    notation:
        - VIAF
    url: http://www.viaf.org/
    EXAMPLES:
      - uri: http://viaf.org/viaf/87772061
      - search: austen
-
    CLASS: Iconclass
    uri: bartoc.org/en/node/459
    url: http://www.iconclass.nl/
    identifier:
        - http://iconclass.org/rdf/2011/09/
    prefLabel:
        en: Iconclass
    license:
        - uri: http://opendatacommons.org/licenses/odbl/1.0/
        - uri: http://opendatacommons.org/licenses/dbcl/1.0/
    EXAMPLES:
        - notation: 52D1
        - notation: 25F23(+46) 
        - uri: http://iconclass.org/25F23(LION)(%2B46)

