GND:
    about: Gemeinsame Normdatei
    examples:
      - uri: http://d-nb.info/gnd/4189143-0
      - notation: 118509624

OpenSKOS:
    about: Europeana OpenSKOS API
    url: http://skos.europeana.eu/api
    examples:
      - uri: http://data.europeana.eu/concept/loc
      - uri: http://id.loc.gov/authorities/subjects/sh2007003224
      - notation: 1500

Wikidata:
    url: https://www.wikidata.org/
    examples:
      - notation: Q42
      - uri: http://www.wikidata.org/entity/Q36578

BARTOC:
    url: http://bartoc.org/
    examples:
      - uri: http://bartoc.org/en/node/430
      - uri: http://bartoc.org/en/node/109
